<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="utf-8">
	<title>Calcul</title>
	<link rel="stylesheet" type="text/css" href="styles.css">
</head>

<body>
	<h1>Calcul</h1>

	<h3>Addition</h3>
		
		
			<div id="probleme"></div>
			<input type="number" id="number_field" name="rep_user">
			<button type="button" id="submit_btn" onclick="OnButtonClick();">Submit</button>
			<div id="result"></div>
			<button type="button" id="next_btn" onclick="OnButtonNextClick();">Suivant</button>
		


	<script type="text/javascript" src="script.js"></script>
</body>
</html>